import "@unocss/reset/tailwind.css"
import "../uno.css"

import { Inter } from "next/font/google"
const inter = Inter({ subsets: ["latin"] })

const metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
}

const RootLayout = ({
	children
}: {
	children: React.ReactNode
}): JSX.Element => {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	)
}

export default RootLayout
export { metadata }
